[template]
cargo_generate_version = ">=0.18.0"


[placeholders.project-description]
type = "string"
prompt = "Project description"
default = "A web application built with the MATH stack"

[placeholders.project-author]
type = "string"
prompt = "Project author"

[placeholders.project-email]
type = "string"
prompt = "Author email"
